=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.FUNC.003.5/rte_config/ConfigEventsConstraints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 U (http://www.altova.com) by PSA (PSA / PCA PEUGEOT CITROEN) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="EVENT-Type">
		<xs:sequence>
			<xs:element name="SHORT-NAME" type="xs:string"/>
			<xs:element name="EVENT-REF">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="REF">
							<xs:attribute name="DEST" type="EVENT-REF-ENUM" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="DURATION" type="xs:decimal" minOccurs="0"/>
			<xs:element name="UNMAPPED" type="xs:boolean" minOccurs="0"/>
			<xs:element name="EVENTS-CALLED" type="EVENTS-REFType" minOccurs="0"/>
			<xs:element name="AFTER-EVENT-REF" type="EVENTS-REFType" minOccurs="0"/>
			<xs:element name="BEFORE-EVENT-REF" type="EVENTS-REFType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="CONFIG-EVENTS-CONSTRAINTS">
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:element name="EVENT" type="EVENT-Type" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="EVENT-REF-ENUM">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ABSTRACT-EVENT"/>
			<xs:enumeration value="ASYNCHRONOUS-SERVER-CALL-RETURNS-EVENT"/>
			<xs:enumeration value="BACKGROUND-EVENT"/>
			<xs:enumeration value="BSW-ASYNCHRONOUS-SERVER-CALL-RETURNS-EVENT"/>
			<xs:enumeration value="BSW-BACKGROUND-EVENT"/>
			<xs:enumeration value="BSW-DATA-RECEIVED-EVENT"/>
			<xs:enumeration value="BSW-EVENT"/>
			<xs:enumeration value="BSW-EXTERNAL-TRIGGER-OCCURRED-EVENT"/>
			<xs:enumeration value="BSW-INTERNAL-TRIGGER-OCCURRED-EVENT"/>
			<xs:enumeration value="BSW-MODE-MANAGER-ERROR-EVENT"/>
			<xs:enumeration value="BSW-MODE-SWITCH-EVENT"/>
			<xs:enumeration value="BSW-MODE-SWITCHED-ACK-EVENT"/>
			<xs:enumeration value="BSW-OPERATION-INVOKED-EVENT"/>
			<xs:enumeration value="BSW-SCHEDULE-EVENT"/>
			<xs:enumeration value="BSW-TIMING-EVENT"/>
			<xs:enumeration value="DATA-RECEIVE-ERROR-EVENT"/>
			<xs:enumeration value="DATA-RECEIVED-EVENT"/>
			<xs:enumeration value="DATA-SEND-COMPLETED-EVENT"/>
			<xs:enumeration value="DATA-WRITE-COMPLETED-EVENT"/>
			<xs:enumeration value="EXTERNAL-TRIGGER-OCCURRED-EVENT"/>
			<xs:enumeration value="INIT-EVENT"/>
			<xs:enumeration value="INTERNAL-TRIGGER-OCCURRED-EVENT"/>
			<xs:enumeration value="MODE-SWITCHED-ACK-EVENT"/>
			<xs:enumeration value="OPERATION-INVOKED-EVENT"/>
			<xs:enumeration value="RTE-EVENT"/>
			<xs:enumeration value="SWC-MODE-MANAGER-ERROR-EVENT"/>
			<xs:enumeration value="SWC-MODE-SWITCH-EVENT"/>
			<xs:enumeration value="TIMING-EVENT"/>
			<xs:enumeration value="TRANSFORMER-HARD-ERROR-EVENT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="REF">
		<xs:annotation>
			<xs:documentation/>
			<xs:appinfo source="tags">mmt.qualifiedName="Ref";xml.xs.customType="REF";xml.xs.pattern="/?[a-zA-Z][a-zA-Z0-9_]{0,127}(/[a-zA-Z][a-zA-Z0-9_]{0,127})*";xml.xs.type="string"</xs:appinfo>
			<xs:appinfo source="stereotypes">atpObject,primitive</xs:appinfo>
			<xs:appinfo source="constraint_2552">Index attribute is only valid for arrays ⌈The index attribute in references is valid only if the reference target is an ApplicationArrayElement or if the reference target is an ImplementationDataTypeElement owned by an ImplementationDataType/ImplementationDataTypeElement of category ARRAY and has an attribute maxNumberOfElements/arraySize.⌋</xs:appinfo>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="REF--SIMPLE"/>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="REF--SIMPLE">
		<xs:restriction base="xs:string">
			<xs:pattern value="/?[a-zA-Z][a-zA-Z0-9_]{0,127}(/[a-zA-Z][a-zA-Z0-9_]{0,127})*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="EVENT" type="EVENT-Type"/>
	<xs:complexType name="EVENTS-REFType">
		<xs:sequence>
			<xs:element name="EVENT-REF" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="REF">
							<xs:attribute name="DEST" type="EVENT-REF-ENUM" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.BUGFIX/in/ASWC_A7C.RteEvent.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<CONFIG-EVENTS-CONSTRAINTS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigEventsConstraints.xsd">
    <EVENT>
        <SHORT-NAME>RUNA_GererFonctionANBC_Cyclic</SHORT-NAME>
        <EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A7C/ASWC_A7C/IB_ASWC_A7C/RUNA_GererFonctionANBC_Cyclic</EVENT-REF>
        <DURATION>0.01</DURATION>
    </EVENT>
    <EVENT>
        <SHORT-NAME>RUNA_GestionDiagANBC_Cyclic</SHORT-NAME>
        <EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A7C/ASWC_A7C/IB_ASWC_A7C/RUNA_GestionDiagANBC_Cyclic</EVENT-REF>
        <AFTER-EVENT-REF>
            <EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A7C/ASWC_A7C/IB_ASWC_A7C/RUNA_GererFonctionANBC_Cyclic</EVENT-REF>
        </AFTER-EVENT-REF>
        <DURATION>0.01</DURATION>
    </EVENT>
</CONFIG-EVENTS-CONSTRAINTS>

=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.BUGFIX/in/ASWC_A28.RteEvent.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<CONFIG-EVENTS-CONSTRAINTS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigEventsConstraints.xsd">
    <EVENT>
        <SHORT-NAME>RUNA_GererMenuPerso_Cyclic</SHORT-NAME>
        <EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A28/ASWC_A28/IB_ASWC_A28/RUNA_GererMenuPerso_Cyclic</EVENT-REF>
        <AFTER-EVENT-REF>
            <EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_P28/ASWC_P28/IB_ASWC_P28/RUNP_PresGererMenuPerso_Cyclic</EVENT-REF>
        </AFTER-EVENT-REF>
        <DURATION>0.01</DURATION>
    </EVENT>
    <EVENT>
        <SHORT-NAME>RUNI_A28_EXIT</SHORT-NAME>
        <EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A28/ASWC_A28/IB_ASWC_A28/RUNI_A28_EXIT</EVENT-REF>
        <DURATION>0.01</DURATION>
    </EVENT>
</CONFIG-EVENTS-CONSTRAINTS>

=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.GEN.006.3/rte_config/ExempleEventsConstraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 U (http://www.altova.com)-->
<CONFIG-EVENTS-CONSTRAINTS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigEventsConstraints.xsd">
	<EVENT>
		<SHORT-NAME>DataReceived1Event</SHORT-NAME>
		<EVENT-REF DEST="TIMING-EVENT">/RootP_Mode/ApplicationModeGroup/APP_WAKEUP</EVENT-REF>
		<DURATION>0.05</DURATION>
	</EVENT>
	<EVENT>
		<SHORT-NAME>DataReceived2Event</SHORT-NAME>
		<EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/DataReceived2Event</EVENT-REF>
		<!--BEFORE-EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/RUNPI_ASWC_A26_ENTRY</BEFORE-EVENT-REF-->
		<!--EVENTS-CALLED DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/RUNPI_ASWC_A26_ENTRY</EVENTS-CALLED-->
	</EVENT>
	<EVENT>
		<SHORT-NAME>DataReceived3Event</SHORT-NAME>
		<EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/DataReceived3Event</EVENT-REF>
		<BEFORE-EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/DataReceived2Event</BEFORE-EVENT-REF>
		<BEFORE-EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/DataReceived1Event</BEFORE-EVENT-REF>
	</EVENT>
</CONFIG-EVENTS-CONSTRAINTS>

=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.BUGFIX/in/ASWC_A7D3.RteEvent.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<CONFIG-EVENTS-CONSTRAINTS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigEventsConstraints.xsd">
    <EVENT>
        <SHORT-NAME>RUNA_AlertesFAP_Cyclic</SHORT-NAME>
        <EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A7D3/ASWC_A7D3/IB_ASWC_A7D3/RUNA_AlertesFAP_Cyclic</EVENT-REF>
        <DURATION>0.01</DURATION>
    </EVENT>
    <EVENT>
        <SHORT-NAME>RUNA_MajVolumeCarb_Cyclic</SHORT-NAME>
        <EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A7D3/ASWC_A7D3/IB_ASWC_A7D3/RUNA_MajVolumeCarb_Cyclic</EVENT-REF>
        <DURATION>0.01</DURATION>
    </EVENT>
    <EVENT>
        <SHORT-NAME>RUNA_TransCMM_Cyclic</SHORT-NAME>
        <EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A7D3/ASWC_A7D3/IB_ASWC_A7D3/RUNA_TransCMM_Cyclic</EVENT-REF>
        <DURATION>0.01</DURATION>
    </EVENT>
</CONFIG-EVENTS-CONSTRAINTS>

=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.BUGFIX/in/ASWC_A7D1.RteEvent.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<CONFIG-EVENTS-CONSTRAINTS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigEventsConstraints.xsd">
    <EVENT>
        <SHORT-NAME>RUNA_GererAcquisImpedance_Cyclic</SHORT-NAME>
        <EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A7D1/ASWC_A7D1/IB_ASWC_A7D1/RUNA_GererAcquisImpedance_Cyclic</EVENT-REF>
        <DURATION>0.01</DURATION>
    </EVENT>
    <EVENT>
        <SHORT-NAME>RUNA_GererJaugeagCarburant_Cyclic</SHORT-NAME>
        <EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A7D1/ASWC_A7D1/IB_ASWC_A7D1/RUNA_GererJaugeagCarburant_Cyclic</EVENT-REF>
        <AFTER-EVENT-REF>
            <EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_P7D/ASWC_P7D/IB_ASWC_P7D/RUNP_P7D_Cyclic</EVENT-REF>
        </AFTER-EVENT-REF>
        <DURATION>0.01</DURATION>
    </EVENT>
    <EVENT>
        <SHORT-NAME>RUNI_A7D1_EXIT</SHORT-NAME>
        <EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A7D1/ASWC_A7D1/IB_ASWC_A7D1/RUNI_A7D1_EXIT</EVENT-REF>
        <DURATION>0.01</DURATION>
    </EVENT>
</CONFIG-EVENTS-CONSTRAINTS>

=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.FUNC.005.2/rte_config/ExempleEventsConstraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 U (http://www.altova.com)-->
<CONFIG-EVENTS-CONSTRAINTS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigEventsConstraints.xsd">
	<EVENT>
		<SHORT-NAME>DataReceivedEvent</SHORT-NAME>
		<EVENT-REF DEST="TIMING-EVENT">/RootP_Mode/ApplicationModeGroup/APP_WAKEUP</EVENT-REF>
		<DURATION>0.05</DURATION>
	</EVENT>
	<EVENT>
		<SHORT-NAME>RUNI_A26_EXIT</SHORT-NAME>
		<EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/RUNI_A26_EXIT</EVENT-REF>
		<!--BEFORE-EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/RUNPI_ASWC_A26_ENTRY</BEFORE-EVENT-REF-->
		<!--EVENTS-CALLED DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/RUNPI_ASWC_A26_ENTRY</EVENTS-CALLED-->
	</EVENT>
	<EVENT>
		<SHORT-NAME>RUNPI_ASWC_A26_ENTRY</SHORT-NAME>
		<EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/RUNPI_ASWC_A26_ENTRY</EVENT-REF>
		<BEFORE-EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/DataReceivedEvent</BEFORE-EVENT-REF>
		<AFTER-EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/RUNI_A26_EXIT</AFTER-EVENT-REF>
	</EVENT>
</CONFIG-EVENTS-CONSTRAINTS>

=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.GEN.005/rte_config/ExempleEventsConstraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 U (http://www.altova.com)-->
<CONFIG-EVENTS-CONSTRAINTS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigEventsConstraints.xsd">
	<EVENT>
		<SHORT-NAME>DataReceived1Event</SHORT-NAME>
		<EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/DataReceived1Event</EVENT-REF>
	</EVENT>
	<EVENT>
		<SHORT-NAME>DataReceived2Event</SHORT-NAME>
		<EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/DataReceived2Event</EVENT-REF>
	</EVENT>
	<EVENT>
		<SHORT-NAME>DataReceived3Event</SHORT-NAME>
		<EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/DataReceived3Event</EVENT-REF>
		<BEFORE-EVENT-REF>
			<EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/DataReceived1Event</EVENT-REF>
		</BEFORE-EVENT-REF>
		<AFTER-EVENT-REF>
			<EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/DataReceived2Event</EVENT-REF>
		</AFTER-EVENT-REF>
	</EVENT>
</CONFIG-EVENTS-CONSTRAINTS>

=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.GEN.003.7/rte_config/ExempleEventsConstraints.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 U (http://www.altova.com)-->
<CONFIG-EVENTS-CONSTRAINTS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigEventsConstraints.xsd">
	<EVENT>
		<SHORT-NAME>RUNA_GererAutomonieConso_Cyclic</SHORT-NAME>
		<EVENT-REF DEST="TIMING-EVENT">/RootP_ASWC_A26/ASWC_A26/IB_ASWC_A26/RUNA_GererAutomonieConso_Cyclic</EVENT-REF>
		<EVENTS-CALLED DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A27/ASWC_A27/IB_ASWC_A27/RUNA_GererCptTempVhl_Cyclic</EVENTS-CALLED>
		<CONTAIN-IMPLICIT-ACCESS>false</CONTAIN-IMPLICIT-ACCESS>
		<DURATION>0.05</DURATION>
		<UNMAPPED>false</UNMAPPED>
	</EVENT>
	<EVENT>
		<SHORT-NAME>RUNA_GererCptTempVhl_Cyclic</SHORT-NAME>
		<EVENT-REF DEST="SWC-MODE-SWITCH-EVENT">/RootP_ASWC_A27/ASWC_A27/IB_ASWC_A27/RUNA_GererCptTempVhl_Cyclic</EVENT-REF>
	</EVENT>
</CONFIG-EVENTS-CONSTRAINTS>
