=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.CHECK.002.4/rte_config/ConfigSwcAllocation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 U (http://www.altova.com) by PSA (PSA / PCA PEUGEOT CITROEN) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="CONFIG-SWC-ALLOCATION">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SWC-ALLOCATION" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="CORE-TYPE-ENUM">
		<xs:restriction base="xs:string">
			<xs:enumeration value="MASTER"/>
			<xs:enumeration value="SECURITY"/>
			<xs:enumeration value="INSTRUM"/>
			<xs:enumeration value="APP_1"/>
			<xs:enumeration value="APP_2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ASIL-TYPE-ENUM">
		<xs:restriction base="xs:string">
			<xs:enumeration value="A"/>
			<xs:enumeration value="B"/>
			<xs:enumeration value="QM"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SWC-REF-ENUM">
		<xs:restriction base="xs:string">
			<xs:enumeration value="APPLICATION-SW-COMPONENT-TYPE"/>
			<xs:enumeration value="ATOMIC-SW-COMPONENT-TYPE"/>
			<xs:enumeration value="COMPLEX-DEVICE-DRIVER-SW-COMPONENT-TYPE"/>
			<xs:enumeration value="COMPOSITION-SW-COMPONENT-TYPE"/>
			<xs:enumeration value="ECU-ABSTRACTION-SW-COMPONENT-TYPE"/>
			<xs:enumeration value="NV-BLOCK-SW-COMPONENT-TYPE"/>
			<xs:enumeration value="PARAMETER-SW-COMPONENT-TYPE"/>
			<xs:enumeration value="SENSOR-ACTUATOR-SW-COMPONENT-TYPE"/>
			<xs:enumeration value="SERVICE-PROXY-SW-COMPONENT-TYPE"/>
			<xs:enumeration value="SERVICE-SW-COMPONENT-TYPE"/>
			<xs:enumeration value="SW-COMPONENT-TYPE"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="REF">
		<xs:annotation>
			<xs:documentation/>
			<xs:appinfo source="tags">mmt.qualifiedName="Ref";xml.xs.customType="REF";xml.xs.pattern="/?[a-zA-Z][a-zA-Z0-9_]{0,127}(/[a-zA-Z][a-zA-Z0-9_]{0,127})*";xml.xs.type="string"</xs:appinfo>
			<xs:appinfo source="stereotypes">atpObject,primitive</xs:appinfo>
			<xs:appinfo source="constraint_2552">Index attribute is only valid for arrays ⌈The index attribute in references is valid only if the reference target is an ApplicationArrayElement or if the reference target is an ImplementationDataTypeElement owned by an ImplementationDataType/ImplementationDataTypeElement of category ARRAY and has an attribute maxNumberOfElements/arraySize.⌋</xs:appinfo>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="REF--SIMPLE"/>
		</xs:simpleContent>
	</xs:complexType>
	<xs:simpleType name="REF--SIMPLE">
		<xs:restriction base="xs:string">
			<xs:pattern value="/?[a-zA-Z][a-zA-Z0-9_]{0,127}(/[a-zA-Z][a-zA-Z0-9_]{0,127})*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="SWC-ALLOCATION" type="SWC-ALLOCATIONType"/>
	<xs:complexType name="SWC-ALLOCATIONType">
		<xs:all>
			<xs:element name="SWC-REF">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="REF">
							<xs:attribute name="DEST" type="SWC-REF-ENUM" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="CORE" type="CORE-TYPE-ENUM"/>
			<xs:element name="PARTITION" type="ASIL-TYPE-ENUM"/>
		</xs:all>
	</xs:complexType>
</xs:schema>

=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.BUGFIX/in/allocation.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<CONFIG-SWC-ALLOCATION xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigSwcAllocation.xsd">
 <SWC-ALLOCATION>
  <SWC-REF DEST="PARAMETER-SW-COMPONENT-TYPE">/RootP_PSWC_ParamDefinition/PSWC_ParamDefinition</SWC-REF>
  <CORE>CORE0</CORE>
  <PARTITION>QM</PARTITION>
 </SWC-ALLOCATION>
 <SWC-ALLOCATION>
  <SWC-REF DEST="APPLICATION-SW-COMPONENT-TYPE">/RootP_ASWC_ParamServer/ASWC_ParamServer</SWC-REF>
  <CORE>CORE0</CORE>
  <PARTITION>QM</PARTITION>
 </SWC-ALLOCATION>
</CONFIG-SWC-ALLOCATION>

=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.BUGFIX/in/SwcAllocation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 U (http://www.altova.com)-->
<CONFIG-SWC-ALLOCATION xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigSwcAllocation.xsd">
	<SWC-ALLOCATION>
		<SWC-REF DEST="SERVICE-SW-COMPONENT-TYPE">/AUTOSAR_BswM/SwComponentTypes_OsApp_CORE0_QM/BswM_OsApp_CORE0_QM</SWC-REF>
		<CORE>CORE0</CORE>
		<PARTITION>QM</PARTITION>
	</SWC-ALLOCATION>
	<SWC-ALLOCATION>
		<SWC-REF DEST="SERVICE-SW-COMPONENT-TYPE">/AUTOSAR_ComM/SwComponentTypes/ComM</SWC-REF>
		<CORE>CORE0</CORE>
		<PARTITION>QM</PARTITION>
	</SWC-ALLOCATION>
	<SWC-ALLOCATION>
		<SWC-REF DEST="SERVICE-SW-COMPONENT-TYPE">/AUTOSAR_Det/SwComponentTypes/DevelopmentErrorTracer</SWC-REF>
		<CORE>CORE0</CORE>
		<PARTITION>QM</PARTITION>
	</SWC-ALLOCATION>
	<SWC-ALLOCATION>
		<SWC-REF DEST="SERVICE-SW-COMPONENT-TYPE">/AUTOSAR_BswM/SwComponentTypes_OsApp_CORE1_QM/BswM_OsApp_CORE1_QM</SWC-REF>
		<CORE>CORE0</CORE>
		<PARTITION>QM</PARTITION>
	</SWC-ALLOCATION>
</CONFIG-SWC-ALLOCATION>

=== TrellixVulnTeam/RTEConfig_I06T/tests/TRS.RTECONFIG.CHECK.001/rte_config/ExempleSwcAllocation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 U (http://www.altova.com)-->
<CONFIG-SWC-ALLOCATION xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation=".\ConfigSwcAllocation.xsd">
	<SWC-ALLOCATION>
		<SWC-REF DEST="APPLICATION-SW-COMPONENT-TYPE">/RootP_ASWC_A26/ASWC_A26</SWC-REF>
		<CORE>APP_2</CORE>
		<PARTITION>A</PARTITION>
	</SWC-ALLOCATION>
	<SWC-ALLOCATION>
		<SWC-REF DEST="APPLICATION-SW-COMPONENT-TYPE">/RootP_ASWC_A27/ASWC_A27</SWC-REF>
		<CORE>APP_1</CORE>
		<PARTITION>A</PARTITION>
	</SWC-ALLOCATION>
	<SWC-ALLOCATION>
		<SWC-REF DEST="APPLICATION-SW-COMPONENT-TYPE">/RootP_ASWC_A28/ASWC_A28</SWC-REF>
		<CORE>APP_1</CORE>
		<PARTITION>A</PARTITION>
	</SWC-ALLOCATION>
</CONFIG-SWC-ALLOCATION>
